//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_banhang.Models.mModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Combo
    {
        public int ID { get; set; }
        public string Combo_Name { get; set; }
        public string Product_List { get; set; }
        public string startDate { get; set; }
        public string endDate { get; set; }
        public int totalMoney { get; set; }
        public string discount { get; set; }
        public int discountMoney { get; set; }
    }
}
