//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_banhang.Models.mModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string ID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public bool gender { get; set; }
        public string birthDate { get; set; }
        public string address { get; set; }
        public string joinDate { get; set; }
        public string Role_ID { get; set; }
    }
}
