//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_banhang.Models.mModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        public int Invoice_ID { get; set; }
        public int Product_ID { get; set; }
        public Nullable<int> Combo_ID { get; set; }
        public int Amount { get; set; }
        public int Price { get; set; }
    }
}
