//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_banhang.Models.mModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int ID { get; set; }
        public string Invoice_Name { get; set; }
        public int Customer_ID { get; set; }
        public Nullable<int> Shipper_ID { get; set; }
        public string totalMoney { get; set; }
        public string createdDate { get; set; }
        public string customerAddress { get; set; }
        public int status { get; set; }
        public string shipDate { get; set; }
    }
}
