//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_banhang.Models.mModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage
    {
        public int Product_ID { get; set; }
        public int Amount { get; set; }
        public string importDate { get; set; }
        public string exportDate { get; set; }
    }
}
